package cangjieGateway

// import std.collection.ArrayList

// main(): Int64 {
//     // 配置后端服务器地址
//     let backendServers = ArrayList([
//         TcpServerAddress("127.0.0.1", 8080),
//         TcpServerAddress("127.0.0.1", 8081),
//         TcpServerAddress("127.0.0.1", 8082)
//     ])

//     // 启动代理服务器
//     let proxyServer = TcpProxyServer(80, backendServers)
//     proxyServer.start()

//     return 0
// }